### ISSUE TITLE
Porting this to River

### ISSUE THREAD

**Issue by MaxHalford** [microprediction/precise#10]
Hello there! I hope you're doing well.

I recently saw this repo pop up and I like it very much. There are some things that we don't yet have in River. In particular, I'm thinking of the `OnlineEmpiricalCovariance` class.

Would it be ok if we ported some of this stuff into [River](https://github.com/online-ml/river/)? I rather ask a gentleman rather savagely copy the code.

Kind regards.

**Comment by microprediction** [comment]
Hi @MaxHalford 

    Savagely copying is fine. Aside: the only reason I'm avoiding classes is due to quirks of my deployment - a desire to avoid object serialization issues. 

     With a little help, this old dog could probably be taught how to make useful PR's to river. I was thinking the same thing with some of the online timeseries stuff I'm doing, although I couldn't quite grok how to do k-step ahead things. If I understand correctly, k=1 step ahead is pretty straightforward in river and that's the focus of "precise". 

Peter

**Comment by microprediction** [comment]
ps: don't forget to enter M6. I'd like to see some open-source devs win prizes!

**Comment by MaxHalford** [comment]
> With a little help, this old dog could probably be taught how to make useful PR's to river. I was thinking the same thing with some of the online timeseries stuff I'm doing, although I couldn't quite grok how to do k-step ahead things. If I understand correctly, k=1 step ahead is pretty straightforward in river and that's the focus of "precise", so it seems like a good idea to join forces there.

It would great if we could work something out. You definitely seem like you have strong coding abilities. The only thing is that River operates on dicts, not numpy arrays. We do use numpy arrays, but only for mini-batch updates. For instance see [`StandardScaler`](https://github.com/online-ml/river/blob/main/river/preprocessing/scale.py#L78).

I would say that including these methods in River, and participating in the project, would maybe allow to reach a wider audience. For instance, I know a few teams that would enjoy having an online covariance matrix for anomaly detection purposes.

> Some methods like online Ledoit-Wolf [here](https://github.com/microprediction/precise/blob/main/precise/skaters/covariance/ewalwfactory.py) are speculative. Up to you if you want to see how the Elo ratings pan out.

It's good you point that out. We do try to focus on established methods, a bit like scikit-learn. We also have a [river-extra](https://github.com/online-ml/river-extra) repository for more "experimental" stuff.

> ps: don't forget to enter M6. I'd like to see some open-source devs win prizes!

Yep it's on my list ;)

**Comment by MaxHalford** [comment]
Will do 👌

**Comment by MaxHalford** [comment]
Ok I'm done, [here it is](https://github.com/online-ml/river/blob/main/river/misc/cov_matrix.py). Let me know if you have any questions!

*Nota bene: I have had on my todo list since far too long to into microprediction.com. It will get done at some point :)*

Keep up the great work 🤝

**Comment by MaxHalford** [comment]
Question for you because I'm blind and can't find it: do you have online formulas for the online precision matrix? That would enable many other algorithms, in particular Bayesian methods.

**Comment by microprediction** [comment]
Hi @MaxHalford I somehow missed this thread, probably under 50000 system alerts killing my inbox.

**Comment by microprediction** [comment]
Massively delayed answer to your question about precision - I don't yet have precision skaters but I think the method used by Lee and Zhong might be of interest:   https://github.com/microprediction/precise/blob/main/precise/skaters/covariance/ewalzfactory.py

**Comment by microprediction** [comment]
Re river. I would think my first PR would be something like [expon weighted sample cov](https://github.com/microprediction/precise/blob/df3a2dd0dd7b1d4e1e20c26b6ba815f4a7d0597c/precise/skaters/covariance/ewaempfactory.py#L9). Does that make sense?

**Comment by MaxHalford** [comment]
> Hi @MaxHalford I somehow missed this thread, probably under 50000 system alerts killing my inbox.

Don't apologize!

> Massively delayed answer to your question about precision - I don't yet have precision skaters but I think the method used by Lee and Zhong might be of interest: https://github.com/microprediction/precise/blob/main/precise/skaters/covariance/ewalzfactory.py

Thanks, I'll take a look. My current thinking is that the Sherman-Morrison formula can be used. 

> Re river. I would think my first PR would be something like [expon weighted sample cov](https://github.com/microprediction/precise/blob/df3a2dd0dd7b1d4e1e20c26b6ba815f4a7d0597c/precise/skaters/covariance/ewaempfactory.py#L9). Does that make sense?

Sure, that would be most appreciated! We have added an online covariance matrix, which you can see [here](https://riverml.xyz/dev/api/misc/CovMatrix/). Under the hood it simply orchestrates a bunch of [`Cov`s](https://riverml.xyz/dev/api/stats/Cov/). My instinct would be to do the same with exponentially weighted covariances. But we don't have those yet! We only have expo weighted variances, see [here](https://riverml.xyz/dev/api/stats/EWVar/).

**Comment by microprediction** [comment]
bubbling this up . note to self

**Comment by MaxHalford** [comment]
I've implemented the precision matrix, see [here](https://riverml.xyz/dev/api/covariance/EmpiricalPrecision/) :)

**Comment by microprediction** [comment]
Very nice !
